---
- hosts: k8s
  remote_user: ubuntu

  tasks:
    - name: set localtime
      command:
        cmd: "sudo rm -f /etc/localtime"

    - name: symbolic link /etc/localtime
      command:
        cmd: "sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime"

    - name: localtime output
      command:
        cmd: "date"
      register: date_output
    - name: SHOW localtime output
      debug:
        msg: "{{ date_output.stdout }}"

    - name: os release
      command:
        cmd: "grep PRETTY_NAME /etc/os-release"
      register: osver_output
    - name: SHOW os release
      debug:
        msg: "{{ osver_output.stdout }}"

    - name: FW status
      command:
        cmd: "sudo ufw status"
      register: ufw_output
    - name: SHOW FW status
      debug:
        msg: "{{ ufw_output.stdout }}"

    - name: SWAP status
      command:
        cmd: "swapon -s"
      register: swapon_output
    - name: SHOW SWAP status
      debug:
        msg: "{{ swapon_output.stdout }}"

    - name: setup_all.sh file copy
      copy:
        src: /home/ec2-user/01.setup_all.sh
        dest: /home/ubuntu/01.setup_all.sh
        owner: ubuntu
        group: ubuntu
        mode: '0640'

    - name: excute setup_all.sh
      command:
        cmd: "sudo sh /home/ubuntu/01.setup_all.sh"

    - name: check needrestart(kernelhints, restart)
      command:
        cmd: "egrep {restart}|{kernelhints} /etc/needrestart/needrestart.conf"
      register: needrestart_output

    - name: SHOW check needrestart(kernelhints, restart)
      debug:
        msg: "{{ needrestart_output.stdout }}"

    - name: check /etc/sysctl.d/k8s.conf
      command:
        cmd: "cat /etc/sysctl.d/k8s.conf"
      register: sysctl_k8s_output

    - name: SHOW /etc/sysctl.d/k8s.conf
      debug:
        msg: "{{ sysctl_k8s_output.stdout }}"

    - name: check modules
      command:
        cmd: "lsmod"
      register: modules_output
    - name: SHOW modules
      debug:
        msg: "{{ modules_output.stdout }}"