---
- hosts: master
  remote_user: ubuntu
  become: true
  become_user: root

  tasks:
    - name: kubeadm init
      shell:
        cmd: sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///var/run/cri-dockerd.sock >> /home/ubuntu/kubeadm_init.log

    - name: Create .kube dir(root user)
      command:
        cmd: mkdir -p /root/.kube

    - name: Copy kubernetes config file(root user)
      command:
        cmd: cp -i /etc/kubernetes/admin.conf /root/.kube/config

    - name: Change file ownership(root user)
      command:
        cmd: chown root:root /root/.kube/config

    - name: Install Calico 1
      command:
        cmd: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml

    - name: Install Calico 2
      command:
        cmd: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/custom-resources.yaml

    - name: Create .kube dir(ubuntu user)
      shell:
        cmd: mkdir -p ~ubuntu/.kube

    - name: Copy kubernetes config file(ubuntu user)
      shell:
        cmd: cp -i /etc/kubernetes/admin.conf ~ubuntu/.kube/config

    - name: Change file ownership(ubuntu user)
      shell:
        cmd: chown -R ubuntu:ubuntu ~ubuntu/.kube

    - name: Install the bash-completion package
      command:
        cmd: apt-get install bash-completion -y

    - name: echo source <(kubectl completion bash) >> /root/.bashrc 
      shell:
        cmd: echo "source <(kubectl completion bash)" >> /root/.bashrc 
