---
- hosts: k8s
  remote_user: ubuntu
  become: true

# 01-1.setup_all.sh script
  tasks:
    - name: Configure the needrestart.conf file - kernelhints
      command:
        cmd: sed -i s,\#\$nrconf{kernelhints} = -1;,\$nrconf{kernelhints} = 0;,g /etc/needrestart/needrestart.conf

    - name: Configure the needrestart.conf file - restart
      command:
        cmd: sed -i s,\#\$nrconf{restart} = 'i';,\$nrconf{restart} = 'l';,g /etc/needrestart/needrestart.conf

    - name: Add module /etc/modules-load.d/k8s.conf
      command:
        cmd: echo "overlay\nbr_netfilter" >> /etc/modules-load.d/k8s.conf

    - name: Load modules - overlay
      command:
        cmd: modprobe overlay

    - name: Load modules - br_netfilter
      command:
        cmd: modprobe br_netfilter

    - name: Setup system parameters - net.bridge.bridge-nf-call-iptables
      command:
        cmd: echo "net.bridge.bridge-nf-call-iptables  = 1" >> /etc/sysctl.d/k8s.conf

    - name: Setup system parameters - net.bridge.bridge-nf-call-ip6tables
      command:
        cmd: echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/k8s.conf

    - name: Setup system parameters - net.ipv4.ip_forward
      command:
        cmd: echo "net.ipv4.ip_forward                 = 1" >> /etc/sysctl.d/k8s.conf

    - name: Apply system parameter
      command:
        cmd: sysctl --system