---
- hosts: master
  remote_user: ubuntu
  become: true

  tasks:
    - name: kubectl get pods -n calico-system
      command:
        cmd: kubectl get pods -n calico-system >> /home/ubuntu/calico_status.log

    - name: kubectl get nodes
      command:
        cmd: kubectl get nodes >> /home/ubuntu/kubectl_nodes.log

    - name: Download calicoctl
      command:
        cmd: curl -L https://github.com/projectcalico/calico/releases/download/v3.24.1/calicoctl-linux-amd64 -o calicoctl

    - name: Add excute permission
      command:
        cmd: chmod +x calicoctl

    - name: Move calicoctl
      command:
        cmd: mv calicoctl /usr/bin/

    - name: calicoctl get 1
      command:
        cmd: calicoctl get ippool -o wide >> /home/ubuntu/calico_status.log

    - name: Copy ipipmode.yaml file
      copy:
        src: /home/ec2-user/j100ansible/ipipmode.yaml
        dest: /home/ubuntu/ipipmode.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0740'

    - name: calicoctl apply -f ipipmode.yaml
      command:
        cmd: calicoctl apply -f ipipmode.yaml >> /home/ubuntu/calico_status.log

    - name: calicoctl get 2
      command:
        cmd: calicoctl get ippool -o wide >> /home/ubuntu/calico_status.log
