---
- hosts: master
  remote_user: ubuntu
  become: true

  tasks:
    - name: Export RELEASE variable
      shell:
        cmd: curl -s https://api.github.com/repos/etcd-io/etcd/releases/latest|grep tag_name | cut -d '"' -f 4
      register: RELEASE

    - name: Download etcd
      shell:
        cmd: wget https://github.com/etcd-io/etcd/releases/download/"{{RELEASE.stdout}}"/etcd-"{{RELEASE.stdout}}"-linux-amd64.tar.gz

    - name: Extract tar file
      shell:
        cmd: tar xf etcd-"{{RELEASE.stdout}}"-linux-amd64.tar.gz

    - name: Change directory and Move files
      shell:
        cmd: cd etcd-"{{RELEASE.stdout}}"-linux-amd64; mv etcd etcdctl etcdutl /usr/local/bin/

    - name: etcdctl version
      shell:
        cmd: etcdctl version  >> etcd_util.log

    - name: etcd --version
      shell:
        cmd: etcd --version  >> etcd_util.log

    - name: echo source <(kubectl completion bash) >> /ubuntu/.bashrc 
      shell:
        cmd: echo "source <(kubectl completion bash)" >> /home/ubuntu/.bashrc 

    - name: kubectl get nodes
      shell:
        cmd: kubectl get nodes >> /home/ubuntu/kubectl_nodes.log
