---
- hosts: k8s
  remote_user: ubuntu
  become: true

# 01-3.setup_all.sh script
  tasks:
    - name: apt update
      command:
        cmd: sudo apt-get update

    - name: Install apt-transport-https, ca-certificates, curl
      command:
        cmd: sudo apt-get install -y apt-transport-https ca-certificates curl

    - name: Download the Google Cloud public signing key
      command:
        cmd: sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Copy kubernetes.list file
      copy:
        src: /home/ec2-user/j100ansible/kubernetes.list
        dest: /etc/apt/sources.list.d/kubernetes.list
        owner: root
        group: root
        mode: '0644'

    - name: apt update
      command:
        cmd: sudo apt-get update

    - name: Install kubelet, kubeadm, kubectl
      command:
        cmd: sudo apt-get install -y kubelet kubeadm kubectl

    - name: apt-mark hold kubelet, kubeadm, kubectl
      command:
        cmd: sudo apt-mark hold kubelet kubeadm kubectl